fix for failed download with no subtitles
At the moment if video doesn't have subtitles `youtube-dl` fails with ... 

```js
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: : video doesn't have subtitles

    at /test/youtube-dl/lib/youtube-dl.js:122:23
    at ChildProcess.exithandler (child_process.js:645:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)
```

... this fix catches and removes possible options passed by the user and tries once to download video only without the subtitles.